In [3]:
pip install Pyvi

     |████████████████████████████████| 8.5MB 78kB/s 
     |████████████████████████████████| 747kB 43.6MB/s 


In [4]:
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from pyvi import ViTokenizer
import string
from google.colab import drive
import re
import os
import keras
from collections import OrderedDict
from keras.models import Sequential
from keras.layers import Dense, Embedding, BatchNormalization, LSTM, Dropout
drive.mount('/content/gdrive')
path = "gdrive/My Drive/Assignment/train/Da/"


Using TensorFlow backend.


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
def clean_document(doc):
    doc = ViTokenizer.tokenize(doc) #Pyvi Vitokenizer library
    doc = doc.lower() #Lower
    tokens = doc.split() #Split in_to words
    table = str.maketrans('', '', string.punctuation.replace("_", "")) #Remove all punctuation
    tokens = [w.translate(table) for w in tokens]
    tokens = [word for word in tokens if word]
    return tokens

In [1]:
import os
INPUT_LENGTH = 50
sequences = []
for f in os.listdir(path): 
    f1 = open(path+f, encoding='utf-16')
    doc = f1.read()
    print(doc)
    tokens = clean_document(doc)
    for i in range(INPUT_LENGTH + 1, len(tokens)):
        seq = tokens[i-INPUT_LENGTH-1:i]
        line = ' '.join(seq)
        sequences.append(line)
sequences

NameError: ignored

In [0]:
tokenizer = keras.preprocessing.text.Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\]^`{|}~ ')
tokenizer.fit_on_texts(sequences)

In [8]:
tokenizer.word_index

{'da': 1,
 'và': 2,
 'có': 3,
 'bạn': 4,
 'các': 5,
 'cho': 6,
 'làm': 7,
 'để': 8,
 'là': 9,
 'nước': 10,
 'nên': 11,
 'không': 12,
 'kem': 13,
 'dùng': 14,
 'của': 15,
 'khi': 16,
 'những': 17,
 'mặt': 18,
 'nhiều': 19,
 'chất': 20,
 'loại': 21,
 'sẽ': 22,
 'ngày': 23,
 'mụn': 24,
 'làn': 25,
 'cần': 26,
 'bị': 27,
 'hoặc': 28,
 'rửa': 29,
 'trong': 30,
 'với': 31,
 'một': 32,
 'khô': 33,
 'ẩm': 34,
 'hơn': 35,
 'sản_phẩm': 36,
 'gây': 37,
 'nếu': 38,
 'này': 39,
 'được': 40,
 'chống': 41,
 'mỹ_phẩm': 42,
 'việc': 43,
 'nắng': 44,
 'có_thể': 45,
 'giữ': 46,
 'vào': 47,
 'dưỡng': 48,
 'như': 49,
 'còn': 50,
 'sau': 51,
 'lại': 52,
 'phải': 53,
 'nhăn': 54,
 'tốt': 55,
 'lần': 56,
 'mỗi': 57,
 'ăn': 58,
 'sử_dụng': 59,
 'sạch': 60,
 'giúp': 61,
 'trên': 62,
 'đến': 63,
 'nhờn': 64,
 'uống': 65,
 'chăm_sóc': 66,
 'tế_bào': 67,
 'dễ': 68,
 'chỉ': 69,
 'ở': 70,
 'rất': 71,
 'thường': 72,
 'đó': 73,
 'dầu': 74,
 'cũng': 75,
 'từ': 76,
 'sữa': 77,
 '2': 78,
 'mất': 79,
 'sự': 80,
 'trắng': 

In [9]:
sequences_digit = tokenizer.texts_to_sequences(sequences)
sequences_digit 

[[1567,
  61,
  1,
  1559,
  1,
  4,
  345,
  21,
  1,
  72,
  504,
  1532,
  1526,
  116,
  38,
  1,
  4,
  345,
  21,
  33,
  64,
  1485,
  24,
  183,
  75,
  230,
  310,
  49,
  514,
  1455,
  3,
  19,
  508,
  338,
  146,
  43,
  1426,
  91,
  1,
  50,
  3,
  151,
  1409,
  1404,
  1399,
  99,
  146,
  168,
  5,
  96,
  97],
 [61,
  1,
  1559,
  1,
  4,
  345,
  21,
  1,
  72,
  504,
  1532,
  1526,
  116,
  38,
  1,
  4,
  345,
  21,
  33,
  64,
  1485,
  24,
  183,
  75,
  230,
  310,
  49,
  514,
  1455,
  3,
  19,
  508,
  338,
  146,
  43,
  1426,
  91,
  1,
  50,
  3,
  151,
  1409,
  1404,
  1399,
  99,
  146,
  168,
  5,
  96,
  97,
  85],
 [1,
  1559,
  1,
  4,
  345,
  21,
  1,
  72,
  504,
  1532,
  1526,
  116,
  38,
  1,
  4,
  345,
  21,
  33,
  64,
  1485,
  24,
  183,
  75,
  230,
  310,
  49,
  514,
  1455,
  3,
  19,
  508,
  338,
  146,
  43,
  1426,
  91,
  1,
  50,
  3,
  151,
  1409,
  1404,
  1399,
  99,
  146,
  168,
  5,
  96,
  97,
  85,
  73],
 [1559,
  1

In [0]:
vocab_size = len(tokenizer.word_index) + 1

In [12]:
import array 
sequences_digit = np.array(sequences_digit)
X, y = sequences_digit[:,:-1], sequences_digit[:,-1]
print(y)
y = keras.utils.to_categorical(y, num_classes=vocab_size)
print(y)
seq_length = X.shape[1]

[  97   85   73 ...   28 1566   16]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=50))
model.add(BatchNormalization())
model.add(LSTM(512, return_sequences=True))
model.add(LSTM(512))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Dense(vocab_size, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 50, 50)            78550     
_________________________________________________________________
batch_normalization_3 (Batch (None, 50, 50)            200       
_________________________________________________________________
lstm_3 (LSTM)                (None, 50, 512)           1153024   
_________________________________________________________________
lstm_4 (LSTM)                (None, 512)               2099200   
_________________________________________________________________
dense_3 (Dense)              (None, 100)               51300     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 100)              

In [0]:
model.fit(X, y, batch_size=512, epochs=20)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/20
7472/7472 [==============================] - 170s 23ms/step - loss: 7.3692 - accuracy: 0.0012
Epoch 2/20
7472/7472 [==============================] - 172s 23ms/step - loss: 7.1342 - accuracy: 0.0203
Epoch 3/20
7472/7472 [==============================] - 169s 23ms/step - loss: 6.8976 - accuracy: 0.0451
Epoch 4/20
7472/7472 [==============================] - 170s 23ms/step - loss: 6.6432 - accuracy: 0.0685
Epoch 5/20
7472/7472 [==============================] - 173s 23ms/step - loss: 6.3574 - accuracy: 0.0907
Epoch 6/20
7472/7472 [==============================] - 170s 23ms/step - loss: 6.0547 - accuracy: 0.1028
Epoch 7/20
7472/7472 [==============================] - 170s 23ms/step - loss: 5.7385 - accuracy: 0.1255
Epoch 8/20
7472/7472 [==============================] - 170s 23ms/step - loss: 5.4342 - accuracy: 0.1407
Epoch 9/20
7472/7472 [==============================] - 173s 23ms/step - loss: 5.1223 - accuracy: 0.1631
Epoch 10/20
7472/7472 [==============================] 

In [0]:
def preprocess_input(doc):
    tokens = clean_document(doc)
    print('Tokens của câu:',tokens)
    tokens = tokenizer.texts_to_sequences(tokens)
    tokens=np.array(tokens).ravel()
    zeros=np.zeros(50-len(tokens))
    tokens=np.append(zeros,tokens)
    #tokens = keras.preprocessing.sequence.pad_sequences(tokens, maxlen=50, truncating='pre')
    return np.reshape(tokens, (1,50))

In [0]:
def generate_text(text_input, n_words):
    tokens = preprocess_input(text_input)
    for _ in range(n_words):
        next_digit = model.predict_classes(tokens, verbose=0)
        tokens = np.append(tokens, next_digit)
        tokens = np.delete(tokens, 0)
        tokens = np.reshape(tokens, (1, 50))
    
    # Mapping to text  
    tokens = np.reshape(tokens, (50))
    out_word = []
    for token in tokens:
        for word, index in tokenizer.word_index.items():
            if index == token:
                out_word.append(word)
                break
    for i in range(len(out_word)-1):
      if out_word[i]==out_word[i+1]:
        out_word[i]=''
    return ' '.join(out_word)

In [0]:
seq = 'Để giải độc cho da mặt'
print('Câu tìm kiếm:',seq)
print('Kết quả dự đoán:',generate_text(text_input=seq, n_words=18))

Câu tìm kiếm: Để giải độc cho da mặt
Tokens của câu: ['để', 'giải_độc', 'cho', 'da', 'mặt']
Kết quả dự đoán: để giải_độc cho da mặt da bị cần có bảo_vệ da và bạn cần có phải  một phải lớp bằng kem làm
